<a href="https://colab.research.google.com/github/marcomunozq-miaad-uacj/Programacion1Semestre/blob/Programacion1Sem/Pr%C3%A1ctica_15_Datos_Temporales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica # 15: Datos Temporales
Alumno: Marco Antonio Muñoz Quiroz

El objetivo de esta actividad es que los estudiantes practiquen los temas vistos de limpieza y transformación de datos categóricos.

https://github.com/marcomunozq-miaad-uacj/Programacion1Semestre/blob/61c7d15004b2db6764feb1f78be16154b53db18f/Pr%C3%A1ctica_15_Datos_Temporales.ipynb

Instrucciones:

Descarga el archivo airdata.csv, proporcionado en esta tarea. También lo puedes encontrar en recursos.
Crea un notebook en colab y guarda el archivo csv  en tu drive.
Agrega secciones en el colab poniendo como título el nombre de cada ejercicio

### Importamos Dataset

In [44]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [45]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Semestre1/Programacion/Semana6/Airdata.csv')
df.head()

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,1/1/2020 0:00,2.180529,87,1.484318,75.963760,39.23,52.88,62.37
1,1/1/2020 1:00,1.490529,89,2.741678,113.198590,38.30,44.95,52.53
2,1/1/2020 2:00,1.690529,85,3.563818,135.000000,NaN,48.40,54.80
3,1/1/2020 3:00,1.430529,84,2.811690,129.805570,37.28,47.18,50.80
4,1/1/2020 4:00,0.840529,86,1.800000,126.869896,29.97,41.48,54.43

# Ejercicio 01:Tipo de Datos Correcto

### Carga el conjunto de datos airdata.csv y verifica que cada columna tenga el tipo de datos correcto

In [46]:
print("Tipos de datos detectados:\n\n", df.dtypes)
print("\nEl tipo de dato de la columna DateTime se cargo como tipo objeto\n")

Tipos de datos detectados:

 DateTime           object
Temperature       float64
Humidity            int64
Wind_Speed        float64
Wind_Direction    float64
NO2_Location_A    float64
NO2_Location_B    float64
NO2_Location_C    float64
dtype: object

El tipo de dato de la columna DateTime se cargo como tipo objeto

### Si una columna de tipo temporal no está en el tipo de correcto realiza la conversión.

In [47]:
df['DateTime'] = pd.to_datetime(df['DateTime'], errors='coerce')

### Usa dtypes para mostrar que cada columna, principalmente la que contiene datos temporales, está en el tipo de datos correcto

In [48]:
print("Tipos de datos despues de la transformacion:\n\n", df.dtypes)

print("\nAhora el tipo de dato de DateTime es datetime64\n")

Tipos de datos despues de la transformacion:

 DateTime          datetime64[ns]
Temperature              float64
Humidity                   int64
Wind_Speed               float64
Wind_Direction           float64
NO2_Location_A           float64
NO2_Location_B           float64
NO2_Location_C           float64
dtype: object

Ahora el tipo de dato de DateTime es datetime64

### Imprime las primeras tres líneas

In [49]:
df.head(3)

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C
0,2020-01-01 00:00:00,2.180529,87,1.484318,75.96376,39.23,52.88,62.37
1,2020-01-01 01:00:00,1.490529,89,2.741678,113.19859,38.30,44.95,52.53
2,2020-01-01 02:00:00,1.690529,85,3.563818,135.00000,NaN,48.40,54.80

# Ejercicio 02: Extraer componentes de fecha y tiempo

### De la columna 'DateTime' extrae el año, mes, día y hora. Crea una nueva columna para cada componente que extraes

In [50]:
df['Year'] = df['DateTime'].dt.year
df['Month'] = df['DateTime'].dt.month
df['Day'] = df['DateTime'].dt.day
df['Hour'] = df['DateTime'].dt.hour

### Imprime las primeras tres líneas del dataframe que ahora deberá tener 4 nuevas columnas.

In [51]:
df.head(3)

,DateTime,Temperature,Humidity,Wind_Speed,Wind_Direction,NO2_Location_A,NO2_Location_B,NO2_Location_C,Year,Month,Day,Hour
0,2020-01-01 00:00:00,2.180529,87,1.484318,75.96376,39.23,52.88,62.37,2020,1,1,0
1,2020-01-01 01:00:00,1.490529,89,2.741678,113.19859,38.30,44.95,52.53,2020,1,1,1
2,2020-01-01 02:00:00,1.690529,85,3.563818,135.00000,NaN,48.40,54.80,2020,1,1,2

In [52]:
print("\nAqui ya se pueden observas las 4 columnas agregadas anteriormente con el tipo de dato extraido de la columna DateTime\n")

Aqui ya se pueden observas las 4 columnas agregadas anteriormente con el tipo de dato extraido de la columna DateTime

# Ejercicio 03: Aritmética - Suma de Intervalos (timedelta)

### Suma 10 días, 7 horas y 15 minutos a cada elemento de la columna 'DateTime'. Guarda el resultado en una nueva columna y agrega al dataframe.

In [53]:

# Crear un objeto timedelta
delta = pd.to_timedelta("10 days 7 hours 15 minutes")

# Sumarlo a cada fila de DateTime
df['DateTime_Sum'] = df['DateTime'] + delta

### Imprime la columna 'DateTime' y la columna que resulta de sumar 10 días, 7 horas y 15 minutos.

In [54]:
df[['DateTime', 'DateTime_Sum']].head(3)

             DateTime        DateTime_Sum
0 2020-01-01 00:00:00 2020-01-11 07:15:00
1 2020-01-01 01:00:00 2020-01-11 08:15:00
2 2020-01-01 02:00:00 2020-01-11 09:15:00

# Ejercicio 04: Timestamp

### Convierte la columna 'DateTime' la cual tiene un formato de fecha legible a a timestamp Unix. Guarda el resultado en una nueva columna

In [55]:
df['Unix_Timestamp'] = df['DateTime'].astype('int64') // 10**9 #Esto ultimo es la division entera

### Imprime las primeras tres filas de  la columna 'DateTime' y la columna que representa dicha fecha en timestamp Unix

In [56]:
df[['DateTime', 'Unix_Timestamp']].head(3)

             DateTime  Unix_Timestamp
0 2020-01-01 00:00:00      1577836800
1 2020-01-01 01:00:00      1577840400
2 2020-01-01 02:00:00      1577844000